; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                      = 12251216-arm64 macOS                    
[ DataSettings ]
datatype                                 = snNucleotide                            
containsCodingNuc                        = True                                    
MissingBaseSymbol                        = ?                                       
IdenticalBaseSymbol                      = .                                       
GapSymbol                                = -                                       
Labelled Sites                           = All Sites                               
Labels to Include                        =                                         
[ ProcessTypes ]
ppDistEst                                = true                                    
ppPairTaxa                               = true                                    
[ AnalysisSettings ]
Analysis                                 = Distance Estimation                     
Scope                                    = Pairs of taxa                           
Estimate Variance                        = ====================                    
Variance Estimation Method               = Bootstrap method                        
Bootstrap Replicates                     = 1000                                    
Substitution Model                       = ====================                    
Substitutions Type                       = Syn-Nonsynonymous                       
Model/Method                             = Nei-Gojobori method (Jukes-Cantor)      
Substitutions to Include                 = s: Synonymous only                      
Rates and Patterns                       = ====================                    
Rates among Sites                        = Uniform Rates                           
Pattern among Lineages                   = Same (Homogeneous)                      
Data Subset to Use                       = ====================                    
Gaps/Missing Data                        = Pairwise deletion                       
Genetic Code Table                       = Standard                                
Genetic Code                             = FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG
Has Time Limit                           = False                                   
Maximum Execution Time                   = -1                                      