; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                      = 12251216-arm64 macOS                    
[ DataSettings ]
datatype                                 = snNucleotide                            
containsCodingNuc                        = True                                    
MissingBaseSymbol                        = ?                                       
IdenticalBaseSymbol                      = .                                       
GapSymbol                                = -                                       
Labelled Sites                           = All Sites                               
Labels to Include                        =                                         
[ ProcessTypes ]
ppFisherExact                            = true                                    
[ AnalysisSettings ]
Analysis                                 = Fisher's Exact Test of Selection        
Scope                                    = In Sequence Pairs                       
Substitution Model                       = ====================                    
Substitutions Type                       = Syn-Nonsynonymous                       
Model/Method                             = Nei-Gojobori method (Proportion)        
Data Subset to Use                       = ====================                    
Gaps/Missing Data                        = Pairwise deletion                       
Has Time Limit                           = False                                   
Maximum Execution Time                   = -1                                      
