; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                      = 12251216-arm64 macOS                    
[ DataSettings ]
datatype                                 = snNucleotide                            
containsCodingNuc                        = True                                    
MissingBaseSymbol                        = ?                                       
IdenticalBaseSymbol                      = .                                       
GapSymbol                                = -                                       
Labelled Sites                           = All Sites                               
Labels to Include                        =                                         
[ ProcessTypes ]
ppZtest                                  = true                                    
[ AnalysisSettings ]
Analysis                                 = Z-test of Selection                     
Scope                                    = In Sequence Pairs                       
Test Hypothesis (HA: alternative)        = Positive selection (HA: dN  > dS)       
Estimate Variance                        = ====================                    
Variance Estimation Method               = Analytical method                       
Substitution Model                       = ====================                    
Substitutions Type                       = Syn-Nonsynonymous                       
Model/Method                             = Modified Nei-Gojobori method (Jukes-Cantor)
Fixed Transition/Transversion Ratio      = 2.00                                    
Data Subset to Use                       = ====================                    
Gaps/Missing Data                        = Pairwise deletion                       
Has Time Limit                           = False                                   
Maximum Execution Time                   = -1                                      
